<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agx_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="contact@gmatiukhin.site">gmatiukhin</maintainer>
  <license>MIT</license>

  <depend>ros_gz</depend>
  <depend>navigation2</depend>
  <depend>nav2_bringup</depend>
  <depend>rtabmap</depend>
  <depend>rtabmap_slam</depend>
  <depend>pointcloud_to_laserscan</depend>
  <depend>topic_tools</depend>
  <depend>imu_filter_madgwick</depend>
  <depend>realsense2_camera</depend>
  <depend>realsense2_description</depend>
  <depend>rslidar_msg</depend>
  <depend>depth_image_proc</depend>

  <depend>py_robot_nav</depend>
  <depend>scout_description</depend>
  <depend>scout_base</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
